# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = buildTree.o main.o writeTree.o changetree.o
LINKOBJ  = buildTree.o main.o writeTree.o changetree.o
LIBS     = -L"C:/Users/think/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/think/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/think/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/think/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/think/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/think/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/think/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/think/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/think/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) -lm -std=c99
CFLAGS   = $(INCS) -lm -std=c99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

buildTree.o: buildTree.cpp
	$(CPP) -c buildTree.cpp -o buildTree.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

writeTree.o: writeTree.cpp
	$(CPP) -c writeTree.cpp -o writeTree.o $(CXXFLAGS)

changetree.o: changetree.cpp
	$(CPP) -c changetree.cpp -o changetree.o $(CXXFLAGS)
